### ISSUE TITLE
Doesn't see/stra

### ISSUE THREAD

**Issue by bobgates** [BytesRobotics/ros2_t260#7] opened 2020-07-29 15:52 UTC

**Comment by bobgates** [comment] 2020-07-29 15:59
After building, then 
```
ros2 node t260_node info
```
then in another terminal:
```
ros2 lifecycle set /t260_node configure
>> Transitioning failed
```

In the terminal where it was run, ```t260_node``` reports
```
[INFO] [1596037403.052517939] [t260_node]: Configuring T260 Node
[INFO] [1596037403.145169185] [t260_node]: T200 series device detected
Device Serial No: 905312110841
Device physical port: 2-1.1-9
Device FW version: 0.2.0.951
Device Product ID: 0x0B37
[INFO] [1596037403.145514918] [t260_node]: Connecting to device with serial number: 905312110841
[INFO] [1596037403.191280128] [t260_node]: Hardware reset
[INFO] [1596037403.191655134] [t260_node]: No calibration file provided, odom is disabled!
[ERROR] [1596037403.282707847] []: Caught exception in callback for transition 10
[ERROR] [1596037403.282893495] []: Original error: No device connected
[WARN] [1596037403.283088873] []: Error occurred while doing error handling.
```

This is typical of my experience with the T265 in other settings: it is there, code can see it, but when push comes to shove, the application thinks the T265 is ```No device connected`` - this is after telling me the device serial number and enough other info that I know it sees the device.

I suspect this much more to do with the T265 than with ros2_t260, but I thought I'd record my progress here.

**Comment by bobgates** [comment] 2020-07-29 16:06
This is on an ultra96 board running an Arm processor and a linux derived from Ubuntu 18.04, that seems to be an otherwise fairly good ros2 citizen, but no dice with the damned T265.

**Comment by Michael-Equi** [comment] 2020-07-29 16:16
Could you provide the version of librealsense2 you are using? It could be something to do with that since I know in the official realsense node that behavior is much more common and seems to be corrected in the node itself whereas the newer SDK breaks the official node while fixing that issue for me (I am using version 2.36.0-0).

**Comment by bobgates** [comment] 2020-07-29 17:11
I'm on 2.36.0. I just tried the official node, same sort of symptoms:
```
ros2 run realsense_node realsense_node
[INFO] [1596042561.662741124] [camera]: Device's serial number is not set, enabling the default device!
[INFO] [1596042561.706058214] [camera]: Device with serial number 905312110841 was found.
[INFO] [1596042561.706817932] [camera]: Create a node for T265 Camera
2020-07-29 17:09:21,857 WARNING [default] Could not open device Unable to open device interface
2020-07-29 17:09:21,865 WARNING [default] Could not open device Unable to open device interface
2020-07-29 17:09:21,872 WARNING [default] Could not open device Unable to open device interface
terminate called after throwing an instance of 'rs2::error'
  what():  No device connected
```

Again, ```device with serial number ___ was found``` then a few lines later ```No device connected```.

**Comment by Michael-Equi** [comment] 2020-07-29 17:18
Can you try setting the hardware reset parameter to false? Do you have any other realsense cameras plugged in?

**Comment by bobgates** [comment] 2020-07-30 08:46
That worked.

```$ ros2 lifecycle set /t260_node configure
Transitioning successful
```

and on the node:
```
$ ros2 run ros2_t260 t260_node
[INFO] [1596098491.968750141] [t260_node]: Configuring T260 Node
[INFO] [1596098492.034401864] [t260_node]: T200 series device detected
Device Serial No: 905312110841
Device physical port: 2-1.2-17
Device FW version: 0.2.0.951
Device Product ID: 0x0B37
[INFO] [1596098492.034726446] [t260_node]: Connecting to device with serial number: 905312110841
[INFO] [1596098492.034799779] [t260_node]: No calibration file provided, odom is disabled!
```

I'm office bound for the rest of the week, but I'll try to collect some data early next week and see how it works. I'm also in the process of building all the tools on the raspberry pi , Ubuntu 18.04 and will give some feedback on whether this node works there.

What is the repercussion of not doing the hardware reset?

**Comment by Michael-Equi** [comment] 2020-07-30 16:07
It shouldn't really do much since the camera does a software reset when connected to the stream, although I find that if you don't have the ability to unplug it the hardware reset comes in handy when the camera does occasionally act up.

**Comment by Michael-Equi** [comment] 2020-08-01 16:24
Added all this to the README documentation and since the cause of these issues is more in the scope of the Realsense SDK I am  closing it here.

**Closed as completed by Michael-Equi** 2020-08-01 16:24 UTC
Labels: bug
